# This is a basic workflow to help BAND get started with Actions

name: BAND Framework CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" and "develop" branches
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows one to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Checks the URLS in md files
      - name: URL Checker
        uses: paramt/url-checker@v0.2.0
        with:
          files: "README.md,SUPPORT.md"
      
      - name: Broken Link Checker Action
        uses: technote-space/broken-link-checker-action@v1.1.3
